"""empty message

Revision ID: cf23c113c1d4
Revises: dd1a2c8f4b27
Create Date: 2022-12-01 15:43:54.465486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf23c113c1d4'
down_revision = 'dd1a2c8f4b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')

    # ### end Alembic commands ###
